# Directory where all the renders will end up by default
# Leave empty for path relative to source
# Also used as the starting point for the relative path
# Examples:
# `Repo/Funny/`   -> `~/Videos/Clips/Repo/Funny/MyClip.mkv`
# `./Repo/Funny/` -> `SourcePath/Repo/Funny/MyClip.mkv`
output_dir=~/HDD2TB/Videos/Clips

# [C]onstant [R]ate [F]actor controls the visual quality of the output
# It ranges from 0-63, 0 being close to lossless, 63 being low quality
# Value of 30 is a great balance between quality and file size
# Can be dynamically set
crf=30

# Preset represents the effort of compression
# It ranges from 0-13, 0 being highest, 13 being lowest
# 4 is a great balance between speed and file size
preset=4

# Accurate cut results in millisecond perfect cuts, and is highly recommended
# Disabling this results in a fallback to keyframes
# The only downside is the render taking longer to start if mark is far in the video
# This shouldn't be a concern/issue in regular clips, but matters if you are cutting a movie
# Can be dynamically set
accurate_cut=yes

# Switches from the efficient AV1 compression to the lossless cut
# This means that the original encoder, data, etc. are fully preserved
# It results in instant render times, but often significantly larger file sizes
# Can be dynamically set
lossless_cut=no

# Combines all the existing audio tracks into a new one by default
# Useful if you split Desktop and Microphone audio into 2 tracks
# Can be dynamically set
combine_audio=no

# Name of the combined audio track
combined_audio_name=Combined

# Using spaces in names is highly discouraged for ease of use in CLI
# Therefore, Tachytome supports replacing spaces with a different character
# Set to ` `(space) to preserve spaces
# Set to ``(nothing) to remove spaces
space_replacement=_

# Suffix added to the default output name to avoid conflicts
# Set to ``(empty) if rendering to a dir different from where your source footage is
suffix= Remuxed

# Default suffix added to the output name when there's a naming conflict
conflict_suffix= Remuxed

# Container used for the output
# MKV is arguably the best in terms of features
container=mkv

# Will trash the source file when done rendering
# Can be dynamically set
trash_original=yes

# Will show the stats screen when done rendering
show_stats_screen=yes

# Duration for which UI will be shown
stats_osd_time=8
