#Settings
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprctl setcursor Nordzy-cursors-white 30
#exec-once = wl-paste -p --watch wl-copy -p ''
exec-once = wl-paste --watch clapboard store
exec-once = wl-paste -p --watch clapboard store

#Daemons
exec-once = pypr
exec-once = dunst #Not needed when using AGS
exec-once = ydotoold # required for Hyprmouse

#Background
exec-once = /home/nnra/Data/Projects/Unity/Nisualizer/Builds/Linux/Nisualizer.x86_64

#Apps
exec-once = kitty --class Ncmpcpp -e ncmpcpp
