require("hyprland.binds.applications")
require("hyprland.binds.binds")
require("hyprland.binds.layout")
require("hyprland.binds.media")
require("hyprland.binds.screenshot")
require("hyprland.binds.zoom")
