# BEGIN_KITTY_FONTS
font_family		 family="Maple Mono NF CN"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 17
editor nvim
disable_ligatures never

cursor #ACCAE6
cursor_text_color #102840
cursor_shape block
mouse_hide_wait 0
cursor_trail 1
cursor_trail_start_threshold 0
shell_integration no-cursor

url_color #6DA1D8
url_style straight
open_url_with default

window_padding_width 10
confirm_os_window_close 0

foreground #ACCAE6
background #102840
background_opacity 1

selection_foreground #BDDFFF
selection_background #153959

# Black
color0 #102840
color8 #153959
# Red
color1 #BF3030
color9 #D83636
# Green
color2 #60BF30
color10 #6DD836
# Yellow
color3 #BFA730
color11 #D8BB36
# Blue
color4 #3078BF
color12 #3687D8
# Magenta
color5 #8330BF
color13 #9336D8
# Cyan
color6 #608FBF
color14 #6DA1D8
# White
color7 #ACCAE6
color15 #BDDFFF
