# BEGIN_KITTY_FONTS
font_family		 family="Maple Mono NF CN"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 13
editor nvim
disable_ligatures never

cursor #D8DED3
cursor_text_color #4C5843
cursor_shape block
mouse_hide_wait 0
cursor_trail 1
cursor_trail_start_threshold 0
shell_integration no-cursor

url_color #B8C4A9
url_style straight
open_url_with default

window_padding_width 10
confirm_os_window_close 0

foreground #D8DED3
background #4C5843
background_opacity 1.0

selection_foreground #F1F7EB
selection_background #3E4637

# Black
color0 #3E4637
color8 #535E4C
# Red
color1 #4C5844
color9 #627258
# Green
color2 #5A6A50
color10 #6E8461
# Yellow
color3 #958831
color11 #AD9E38
# Blue
color4 #C4B550
color12 #DDCC59
# Magenta
color5 #75806F
color13 #8C9986
# Cyan
color6 #A0AA95
color14 #B8C4A9
# White
color7 #D8DED3
color15 #F1F7EB
