# BEGIN_KITTY_FONTS
font_family		 family="Maple Mono NF CN"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 13
editor nvim
disable_ligatures never

cursor #A3C5CC
cursor_text_color #081D26
cursor_shape block
mouse_hide_wait 0
cursor_trail 1
cursor_trail_start_threshold 0
shell_integration no-cursor

url_color #267F6F
url_style straight
open_url_with default

window_padding_width 10
confirm_os_window_close 0

foreground #A3C5CC
background #081D26
background_opacity 0.5

selection_foreground #B7DCE5
selection_background #0C2E3F

# Black
color0 #081D26
color8 #0C2E3F
# Red
color1 #661F1F
color9 #7F2626
# Green
color2 #1F6628
color10 #267F32
# Yellow
color3 #66661F
color11 #7F7F26
# Blue
color4 #1F5A66
color12 #266F7F
# Magenta
color5 #4D1F66
color13 #5F267F
# Cyan
color6 #1F665A
color14 #267F6F
# White
color7 #A3C5CC
color15 #B7DCE5
