live_config_reload = true

[window]
padding = {x = 10, y = 10}
opacity = 0.9

[font]
normal = { family = "Cascadia Code NF", style = "Regular" }
bold = { family = "Cascadia Code NF", style = "Bold" }
italic = { family = "Cascadia Code NF", style = "Italic" }
bold_italic = { family = "Cascadia Code NF", style = "Bold Italic" }
size = 15

[colors]
footer_bar = { foreground = "#ECEFF4", background = "#2E3440" }
transparent_background_colors = true

[colors.primary]
foreground = "#ECEFF4"
background = "#2E3440"
dim_foreground = "#D8DEE9"
bright_foreground = "#81A1C1"

[colors.search]
matches = { foreground = "#81A1C1", background = "#2E3440" }
focused_match = { foreground = "#EBCB8B", background = "#2E3440" }

[colors.hints]
start = { foreground = "#ECEFF4", background = "#2E3440" }
end = { foreground = "#D8DEE9", background = "#2E3440" }

[colors.normal]
black = "#2E3440"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#5E81AC"
magenta = "#B48EAD"
cyan = "#88C0D0"
white = "#D8DEE9"

[colors.bright]
black = "#3B4252"
red = "#D08770"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#ECEFF4"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

#alacritty-smooth-cursor settings
#smooth_motion = true
#smooth_motion_factor = 0.2
#smooth_motion_spring = 0.5
