[general]
live_config_reload = true

[window]
padding = {x = 10, y = 10}
opacity = 1

[font]
normal = { family = "Courier Prime Code", style = "Regular" }
bold = { family = "Courier Prime Code", style = "Bold" }
italic = { family = "Courier Prime Code", style = "Italic" }
bold_italic = { family = "Courier Prime Code", style = "Bold Italic" }
size = 17

[colors]
footer_bar = { foreground = "#B2B2B2", background = "#080808" }
transparent_background_colors = true

[colors.primary]
foreground = "#B2B2B2"
background = "#080808"
dim_foreground = "#8C8C8C"
bright_foreground = "#CBCBCB"

[colors.search]
matches = { foreground = "#B2B2B2", background = "#080808" }
focused_match = { foreground = "#CBCBCB", background = "#080808" }

[colors.hints]
start = { foreground = "#B2B2B2", background = "#080808" }
end = { foreground = "#8C8C8C", background = "#080808" }

[colors.normal]
black = "#080808"
red = "#990000"
green = "#00990D"
yellow = "#998000"
blue = "#006699"
magenta = "#990099"
cyan = "#008099"
white = "#999999"

[colors.bright]
black = "#212121"
red = "#B20000"
green = "#00B20E"
yellow = "#B29400"
blue = "#0077B2"
magenta = "#B200B2"
cyan = "#0094B2"
white = "#B2B2B2"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

#alacritty-smooth-cursor settings
#smooth_motion = true
#smooth_motion_factor = 0.2
#smooth_motion_spring = 0.5
