[general]
live_config_reload = true

[window]
padding = {x = 10, y = 10}
opacity = 1

[font]
normal = { family = "Maple Mono NF CN", style = "Regular" }
bold = { family = "Maple Mono NF CN", style = "Bold" }
italic = { family = "Maple Mono NF CN", style = "Italic" }
bold_italic = { family = "Maple Mono NF CN", style = "Bold Italic" }
size = 16

[colors]
footer_bar = { foreground = "#D8DED3", background = "#4C5843" }
transparent_background_colors = true

[colors.primary]
foreground = "#D8DED3"
background = "#4C5843"
dim_foreground = "#B3B7AF"
bright_foreground = "#F1F7EB"

[colors.search]
matches = { foreground = "#D8DED3", background = "#4C5843" }
focused_match = { foreground = "#F1F7EB", background = "#4C5843" }

[colors.hints]
start = { foreground = "#D8DED3", background = "#4C5843" }
end = { foreground = "#B3B7AF", background = "#4C5843" }

[colors.normal]
black = "#3E4637"
red = "#4C5844"
green = "#5A6A50"
yellow = "#958831"
blue = "#C4B550"
magenta = "#75806F"
cyan = "#A0AA95"
white = "#D8DED3"

[colors.bright]
black = "#535E4C"
red = "#627258"
green = "#6E8461"
yellow = "#AD9E38"
blue = "#DDCC59"
magenta = "#8C9986"
cyan = "#B8C4A9"
white = "#F1F7EB"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

#alacritty-smooth-cursor settings
#smooth_motion = true
#smooth_motion_factor = 0.2
#smooth_motion_spring = 0.5
