[general]
live_config_reload = true

[window]
padding = {x = 10, y = 10}
opacity = 1

[font]
normal = { family = "Courier Prime Code", style = "Regular" }
bold = { family = "Courier Prime Code", style = "Bold" }
italic = { family = "Courier Prime Code", style = "Italic" }
bold_italic = { family = "Courier Prime Code", style = "Bold Italic" }
size = 17

[colors]
footer_bar = { foreground = "#ACCAE6", background = "#102840" }
transparent_background_colors = true

[colors.primary]
foreground = "#ACCAE6"
background = "#102840"
dim_foreground = "#8EA7BF"
bright_foreground = "#BDDFFF"

[colors.search]
matches = { foreground = "#ACCAE6", background = "#102840" }
focused_match = { foreground = "#BDDFFF", background = "#102840" }

[colors.hints]
start = { foreground = "#ACCAE6", background = "#102840" }
end = { foreground = "#8EA7BF", background = "#102840" }

[colors.normal]
black = "#102840"
red = "#13304D"
green = "#1A4066"
yellow = "#205080"
blue = "#266099"
magenta = "#2D70B3"
cyan = "#6699CC"
white = "#ACCAE6"

[colors.bright]
black = "#153959"
red = "#174066"
green = "#1F4F7F"
yellow = "#275E99"
blue = "#2C71B2"
magenta = "#3480CB"
cyan = "#72ACE5"
white = "#BDDFFF"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

#alacritty-smooth-cursor settings
#smooth_motion = true
#smooth_motion_factor = 0.2
#smooth_motion_spring = 0.5
