[FileDialog]
history=file:///home/nn, file:///home/nn/HDD2TB/Movies/Constantine, file:///home/nn/Data/Projects/Unity/Kairostasis, file:///home/nn/Data/Projects/Unity/Kairostasis/Kairostasis, file:///home/nn/HDD2TB/Movies/Superman, file:///home/nn/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances
lastVisited=file:///home/nn/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances
qtVersion=6.10.1
shortcuts=file:///home/nn/.config, file:///home/nn/Data/Projects/Editing, file:///home/nn/Data/Projects
sidebarWidth=145
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4\xbd\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x2\xc6\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0w\0\0\0\x1\0\0\0\0\0\0\x1\x3\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
