[FileDialog]
history=file:///home/nnra/HDD500GB/Movies/Troy, file:///home/nnra/HDD500GB/Movies/300, file:///home/nnra/HDD500GB/Movies/DCEU, file:///home/nnra/HDD500GB/Movies/Purge, file:///home/nnra/vienna/resources/[skripte]/[hud], file:///home/nnra/HDD2TB/Autism
lastVisited=file:///home/nnra/HDD2TB/Autism
qtVersion=6.8.1
shortcuts=file:///home/nnra/Documents, file:///home/nnra/Desktop, file:///home/nnra/Downloads, file:///home/nnra
sidebarWidth=193
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\xd8\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xe1\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0w\0\0\0\x1\0\0\0\0\0\0\x1\x3\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)
viewMode=Detail
