[FileDialog]
history=file:///home/nnra/Data/Projects/Unity/Escapeon/Escapeon, file:///home/nnra/HDD2TB/Work/Uni/Homework/CS130/CS130-DZ04-Mateja-Popovic-5962, file:///home/nnra/TestProj, file:///home/nnra/Data/Projects/NNPage, file:///home/nnra/HDD2TB/Movies/Watchmen Ultimate Cut, file:///home/nnra/.local/share/PrismLauncher
lastVisited=file:///home/nnra/.local/share/PrismLauncher
qtVersion=5.15.15
shortcuts=file:///home/nnra/Documents, file:///home/nnra/Desktop, file:///home/nnra/Downloads, file:///home/nnra
sidebarWidth=193
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\xd8\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xe1\0\0\0\x1\0\0\0\0\0\0\0}\0\0\0\x1\0\0\0\0\0\0\0w\0\0\0\x1\0\0\0\0\0\0\x1\x3\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
