# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab


# Parse current commandline:
# - _shtab_trash_restore_cmdpath=(sub)command path seen so far
# - _shtab_trash_restore_npos=number of positional arguments given after it
# - options are skipped based on _shtab_trash_restore_opts_with_value & _shtab_trash_restore_commands lists
function _shtab_trash_restore_scan
  set -g _shtab_trash_restore_cmdpath ''
  set -g _shtab_trash_restore_npos 0
  set -l tokens (commandline -opc)
  set -e tokens[1]
  set -l expect_value 0
  for t in $tokens
    if test $expect_value -eq 1
      set expect_value 0
      continue
    end
    switch "$t"
      case '--*=*'
        continue
      case '-*'
        if contains -- $t $_shtab_trash_restore_opts_with_value
          set expect_value 1
        end
        continue
      case '*'
        if test $_shtab_trash_restore_npos -eq 0
          set -l candidate $t
          if test -n "$_shtab_trash_restore_cmdpath"
            set candidate "$_shtab_trash_restore_cmdpath $t"
          end
          if contains -- $candidate $_shtab_trash_restore_commands
            set -g _shtab_trash_restore_cmdpath $candidate
            continue
          end
        end
        set -g _shtab_trash_restore_npos (math $_shtab_trash_restore_npos + 1)
    end
  end
end

# Condition helper: true if the current (sub)command path equals the given one.
function _shtab_trash_restore_using
  _shtab_trash_restore_scan
  test "$_shtab_trash_restore_cmdpath" = "$argv"
end

set -g _shtab_trash_restore_commands
set -g _shtab_trash_restore_opts_with_value --print-completion --sort

complete -c trash-restore -e
complete -c trash-restore -f

complete -c trash-restore -n _shtab_trash_restore_using -s h -l help -d 'show this help message and exit'
complete -c trash-restore -n _shtab_trash_restore_using -l print-completion -xka "bash zsh tcsh fish" -d 'print shell completion script (default: None)'
complete -c trash-restore -n _shtab_trash_restore_using -l sort -xka "date path none" -d 'Sort list of restore candidates by given field (default: date)'
complete -c trash-restore -n _shtab_trash_restore_using -l version
complete -c trash-restore -n _shtab_trash_restore_using -l overwrite -d 'Overwrite existing files with files coming out of the trash (default: False)'
complete -c trash-restore -n '_shtab_trash_restore_using; and test $_shtab_trash_restore_npos -eq 0' -ka "(__fish_complete_path)" -d 'Restore files from given path instead of current directory (default: )'
