# BEGIN_KITTY_FONTS
font_family		 family="Maple Mono Normal NFP"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 13
editor nvim
disable_ligatures never

cursor #A3C5CC
cursor_text_color #041C26
cursor_shape block
mouse_hide_wait 0
cursor_trail 1
cursor_trail_start_threshold 0
shell_integration no-cursor

url_color #2D998F
url_style straight
open_url_with default

window_padding_width 10
confirm_os_window_close 0

foreground #A3C5CC
background #041C26
background_opacity 0.5

selection_foreground #B7DCE5
selection_background #082E3F

# Black
color0 #041C26
color8 #082E3F
# Red
color1 #80333C
color9 #993D49
# Green
color2 #338051
color10 #3D9961
# Yellow
color3 #668033
color11 #7A993D
# Blue
color4 #267180
color12 #2D8699
# Magenta
color5 #436496
color13 #4D74AF
# Cyan
color6 #268078
color14 #2D998F
# White
color7 #A3C5CC
color15 #B7DCE5
