[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x41\x66ile:///mnt/HDD2TB/Videos/cs%20clips/skit%20skit%20%231%20cit.mov)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\f\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\0\f\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\0\0\0\0\0\0\x14\0\0\0\0\f\0\0\0\f\0\0\t\xf8\0\0\x5\x93)

[Epanel]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3m\0\0\0\f\0\0\x6p\0\0\x1\xe3\0\0\x3m\0\0\0\f\0\0\x6p\0\0\x1\xe3\0\0\0\0\0\0\0\0\x14\0\0\0\x3m\0\0\0\f\0\0\x6p\0\0\x1\xe3)

[FullScreen]
pos=@Point(2160 1374)
screen=@Rect(0 0 5120 1440)
wide=false

[MainWindow]
QtStyle=System's default
adv-controls=0
bgSize=@Size(2541 1330)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Mediainfo]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\0\0\0\0\0\0\x14\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93)

[Messages]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\0\0\0\0\0\0\x14\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93)

[OpenDialog]
advanced=false
size=@Size(682 458)

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3p\0\0\x1r\0\0\bL\0\0\x4\x9c\0\0\x3p\0\0\x1r\0\0\bL\0\0\x4\x9c\0\0\0\0\0\0\0\0\n\0\0\0\x3p\0\0\x1r\0\0\bL\0\0\x4\x9c)

[RecentsMRL]
list=file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2018-01-18.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2018-00-01.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2018-02-44.mkv, file:///home/nnra/Videos/OBS/Replay%202024-11-19%2018-03-06.mkv, file:///home/nnra/Videos/OBS/Replay%202024-11-19%2018-00-01.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-50-36.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-45-53.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-38-38.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-38-00.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-29-07.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-18-03.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-17-28.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-15-24.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-14-47.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-14-20.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-13-21.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-12-59.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-12-42.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-11-24.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-09-40.mkv, file:///home/nnra/Videos/OBS/CS1.6_Admin_Rage/Replay%202024-11-19%2014-06-23.mkv, file:///home/nnra/HDD500GB/Movies/The%20Conjuring/Annabelle.1.2014.ITA.AC3.ENG.DTS.WEBrip.HDR10.HEVC.2160p.mkv, file:///home/nnra/HDD2TB/Videos/Clips/Minecraft/Highlights/Ne_moze_da_score_i_da_se_potrudi.mp4, file:///home/nnra/HDD2TB/Videos/Clips/Minecraft/Highlights/Izbio_Radina_Iz_Portala.mp4, file:///home/nnra/HDD2TB/Videos/Clips/Minecraft/Highlights/DestroyedKalu.mp4, file:///home/nnra/HDD2TB/Videos/Clips/Minecraft/Highlights/DestroKalu.mp4, file:///home/nnra/HDD2TB/Videos/Clips/Minecraft/Highlights/DestroyedDaki%2BScore.mp4, file:///home/nnra/HDD2TB/Videos/Clips/Minecraft/Highlights/ClutchNaDalina.mp4, file:///home/nnra/HDD2TB/Videos/Clips/Minecraft/Funny/Radin_CUCU_CUC_i_MA_PUTIC.mp4, file:///home/nnra/HDD2TB/Videos/Clips/Minecraft/Funny/PutkeSeZnojiWOOOOOOOOOO.mp4
times=0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59901
