[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x41\x66ile:///mnt/HDD2TB/Videos/cs%20clips/skit%20skit%20%231%20cit.mov)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\t\xff\0\0\x5\x9f\0\0\0\0\0\0\0\0\0\0\t\xff\0\0\x5\x9f\0\0\0\0\0\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\t\xff\0\0\x5\x9f)

[Epanel]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3m\0\0\0\f\0\0\x6p\0\0\x1\xe3\0\0\x3m\0\0\0\f\0\0\x6p\0\0\x1\xe3\0\0\0\0\0\0\0\0\x14\0\0\0\x3m\0\0\0\f\0\0\x6p\0\0\x1\xe3)

[FullScreen]
pos=@Point(880 1374)
screen=@Rect(0 0 2560 1440)
wide=false

[MainWindow]
QtStyle=System's default
adv-controls=0
bgSize=@Size(1261 1330)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Mediainfo]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\0\0\0\0\0\0\x14\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93)

[Messages]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\0\0\0\0\0\0\x14\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93)

[OpenDialog]
advanced=false
size=@Size(682 458)

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3p\0\0\x1r\0\0\bL\0\0\x4\x9c\0\0\x3p\0\0\x1r\0\0\bL\0\0\x4\x9c\0\0\0\0\0\0\0\0\n\0\0\0\x3p\0\0\x1r\0\0\bL\0\0\x4\x9c)

[RecentsMRL]
list=file:///home/nnra/Videos/OBS/2024-12-06%2008-45-59.mkv, file:///home/nnra/Videos/OBS/Replay%202024-12-05%2011-07-12.mkv, file:///home/nnra/Videos/OBS/Replay%202024-12-05%2011-03-43.mkv, file:///home/nnra/Videos/OBS/Replay%202024-12-05%2011-26-02.mkv, file:///home/nnra/Videos/OBS/Replay%202024-12-02%2011-09-38.mkv, file:///home/nnra/Videos/OBS/Replay%202024-12-03%2010-54-12.mkv, file:///home/nnra/Data/Projects/Editing/nn/OyOyOyOyOy/Scout_JS_HS_WB.mkv, file:///home/nnra/Videos/OBS/Scout_HS_WB_Dust2_CT.mkv, file:///home/nnra/Videos/OBS/Scout_JS_HS_WB.mkv, file:///home/nnra/Videos/OBS/T_2v1.mkv, file:///home/nnra/Videos/OBS/T_3K_AK.mkv, file:///home/nnra/Videos/OBS/T_JSNSHS.mkv, file:///home/nnra/Videos/OBS/TF2_Double_Kill.mkv, file:///home/nnra/Videos/OBS/USP_JS.mkv, file:///home/nnra/Videos/OBS/USP_HS%2BScout_HS_WB.mkv, file:///home/nnra/Videos/OBS/Trowe_Pushups_2.mkv, file:///home/nnra/Videos/OBS/Trowe_Pushups_1.mkv, file:///home/nnra/Videos/OBS/Russian_Addict_4K.mkv, file:///home/nnra/HDD2TB/Backups/Trowe_Nintendo_SD/Nintendo_Internal/private/ds/app/4B475545/recent10.pls, file:///home/nnra/HDD2TB/Backups/Trowe_Nintendo_SD/Nintendo_Internal/private/ds/app/4B475545/mark1.pls, file:///home/nnra/Videos/OBS/2_AWP_Kill.mkv, file:///home/nnra/Data/Projects/Editing/nn/Kid_Screams_In_Aprogrammation/Troshe_Screaming_2.mkv, file:///home/nnra/Data/Projects/Editing/nn/Kid_Screams_In_Aprogrammation/Troshe_Screaming_1.mkv, file:///home/nnra/Data/SteamLibrary/steamapps/common/Counter-Strike%20Global%20Offensive/csgo/panorama/videos/survival_promo.webm, file:///home/nnra/Data/SteamLibrary/steamapps/common/Counter-Strike%20Global%20Offensive/csgo/panorama/videos/splat.webm, file:///home/nnra/Data/SteamLibrary/steamapps/common/Counter-Strike%20Global%20Offensive/csgo/panorama/videos/anubis.webm, file:///home/nnra/HDD2TB/Work/3D/Blender/Exports/Renders/Essencia/Essencia.mp4, file:///home/nnra/HDD2TB/Work/3D/Blender/Exports/Renders/Essencia/Essencia%20Old.mp4, file:///home/nnra/HDD2TB/Work/3D/Blender/Exports/Renders/Essencia/Essencia%20Growth0001-0900.mp4, file:///home/nnra/HDD2TB/Work/3D/Blender/Exports/Renders/Nordic%20Tiles/Old/Nordic%20Nodes.mp4
times=0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
