[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x41\x66ile:///mnt/HDD2TB/Videos/cs%20clips/skit%20skit%20%231%20cit.mov)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\f\0\0\x2\xd7\0\0\x13\xf3\0\0\x5\x93\0\0\0\f\0\0\x2\xd7\0\0\x13\xf3\0\0\x5\x93\0\0\0\0\0\0\0\0\x14\0\0\0\0\f\0\0\x2\xd7\0\0\x13\xf3\0\0\x5\x93)

[Epanel]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3m\0\0\0\f\0\0\x6p\0\0\x1\xe3\0\0\x3m\0\0\0\f\0\0\x6p\0\0\x1\xe3\0\0\0\0\0\0\0\0\x14\0\0\0\x3m\0\0\0\f\0\0\x6p\0\0\x1\xe3)

[FullScreen]
pos=@Point(2164 1373)
screen=@Rect(0 0 5120 1440)
wide=false

[MainWindow]
QtStyle=System's default
adv-controls=0
bgSize=@Size(5096 615)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Mediainfo]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\0\0\0\0\0\0\x14\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93)

[Messages]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93\0\0\0\0\0\0\0\0\x14\0\0\0\x5\a\0\0\0\f\0\0\t\xf8\0\0\x5\x93)

[OpenDialog]
advanced=false
size=@Size(682 458)

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3p\0\0\x1r\0\0\bL\0\0\x4\x9c\0\0\x3p\0\0\x1r\0\0\bL\0\0\x4\x9c\0\0\0\0\0\0\0\0\n\0\0\0\x3p\0\0\x1r\0\0\bL\0\0\x4\x9c)

[RecentsMRL]
list=file:///home/nnra/Videos/OBS/Replay%202025-02-11%2011-57-25.mkv, file:///home/nnra/Videos/OBS/Replay%202025-02-11%2011-07-14.mkv, file:///home/nnra/Videos/OBS/Replay%202025-02-09%2003-08-20.mkv, file:///home/nnra/HDD2TB/Videos/Clips/CS2/Funny/Djerko_Usao_Je_Troshe_U_Mene_I_Sprayovao.mkv, file:///home/nnra/Data/Black_Adam_Cropped.mkv, file:///home/nnra/HDD2TB/Videos/Clips/Random/Funny/Trowe/TroweSuperJePesma.mkv, file:///home/nnra/Videos/OBS/TroweSuperJePesma.mkv, file:///home/nnra/HDD2TB/Videos/Clips/Roblox/Doors/What_The_Fuck_Even_Happened_Here.mkv, file:///home/nnra/Videos/OBS/Replay%202024-10-05%2013-48-20.mkv, file:///home/nnra/Videos/OBS/Replay%202024-10-04%2010-51-16.mkv, file:///home/nnra/Videos/OBS/Replay%202024-10-04%2010-49-24.mkv, file:///home/nnra/Videos/OBS/Replay%202024-10-04%2010-25-12.mkv, file:///home/nnra/Videos/OBS/Replay%202024-10-04%2010-21-25.mkv, file:///home/nnra/Videos/OBS/Replay%202024-10-04%2010-20-47.mkv, file:///home/nnra/Videos/OBS/Replay%202024-10-04%2010-18-50.mkv, file:///home/nnra/Videos/OBS/Replay%202024-10-04%2010-15-26.mkv, file:///home/nnra/Videos/OBS/Replay%202024-09-13%2018-50-39.mkv, file:///home/nnra/Videos/OBS/Replay%202024-09-13%2018-39-13.mkv, file:///home/nnra/Videos/OBS/Replay%202024-09-13%2018-34-25.mkv, file:///home/nnra/HDD2TB/Videos/Clips/Random/Funny/Pig.mkv, file:///home/nnra/Videos/OBS/Replay%202024-09-13%2017-11-15.mkv, file:///home/nnra/Videos/OBS/Replay%202024-09-08%2004-03-20.mkv, file:///home/nnra/Videos/OBS/Replay%202024-09-08%2004-02-57.mkv, file:///home/nnra/HDD2TB/Videos/Clips/CS2/Highlights/Scout_WB_HS.mkv, file:///home/nnra/HDD2TB/Videos/Clips/CS2/Highlights/Scout_HS_WB%2BNS_HS.mkv, file:///home/nnra/Videos/OBS/Replay%202024-09-08%2004-02-48.mkv, file:///home/nnra/Videos/OBS/Replay%202024-09-07%2007-53-00.mkv, file:///home/nnra/HDD2TB/Videos/Clips/CS2/Funny/Family_Guy_Episode.mkv, file:///home/nnra/Videos/OBS/Replay%202024-09-07%2007-49-24.mkv, file:///home/nnra/Videos/OBS/Replay%202024-08-28%2019-56-37.mkv
times=57673, 0, 0, 0, 116016, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 49200, 0, 0, 0, 0, 0, 0, 0
