hl.env("NVD_BACKEND",               "direct")
hl.env("GBM_BACKEND",               "nvidia-drm")
hl.env("LIBVA_DRIVER_NAME",         "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("__GL_GSYNC_ALLOWED",        "1")
hl.env("__GL_VRR_ALLOWED",          "0")
