[mgr]
ratio = [2, 4, 4]

sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true

show_hidde = false
show_symlink = true

[preview]
wrap = "yes"
tab_size = 4

max_width = 8192
max_height = 8192
image_delay = 0
image_filter = "triangle"
image_quality = 50

[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"

[[plugin.prepend_previewers]]
mime = "audio/*"
run = "exifaudio"

[[plugin.prepend_previewers]]
name = "*.blend"
run = "blender-preview"

[[plugin.prepend_previewers]]
name = "*.blend1"
run = "blender-preview"

[[plugin.prepend_previewers]]
name = "*.kra"
run = "krita-preview"

[[plugin.prepend_previewers]]
name = "*.kra~"
run = "krita-preview"

[[plugin.prepend_previewers]]
url = "*.tar*"
run = 'piper --format=url -- tar tf "$1"'

[[plugin.prepend_previewers]]
url = "*.csv"
run = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
url = "*/"
run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'

[[plugin.prepend_previewers]]
mime = "application/sqlite3"
run  = 'piper -- sqlite3 "$1" ".schema --indent"'

[[plugin.prepend_preloaders]]
name = "*.blend"
run = "blender-preview"

[[plugin.prepend_preloaders]]
name = "*.blend1"
run = "blender-preview"

[[plugin.prepend_preloaders]]
name = "*.kra"
run = "krita-preview"

[[plugin.prepend_preloaders]]
name = "*.kra~"
run = "krita-preview"

