# Keep open and don't autoplay
keep-open=always

# Automatically open all the files in the same dir
autocreate-playlist=same

# Volume
volume=50
volume-max=150

# OSD
title-bar=no
osc=no
osd-bar=no
osd-on-seek=no

# Misc
title-bar=no
demuxer-max-bytes=8GiB
hr-seek=yes
cache=yes
cache-pause=no

# GPU Acceeleration
hwdec=auto
hwdec-codecs=all
gpu-context=auto
vd-lavc-dr=yes
vd-lavc-threads=8

# Scaling
scale=lanczos
cscale=bilinear
dscale=mitchell
correct-downscaling=yes
linear-downscaling=no
sigmoid-upscaling=no

# Interpolation
video-sync=audio

# Debanding
deband=yes
deband-iterations=1
deband-threshold=35
deband-range=16
deband-grain=4

# Color
target-colorspace-hint=yes
gamut-mapping-mode=clip

# Dithering
dither-depth=auto
temporal-dither=yes
dither=fruit

# Autocrop
script-opts-append=autocrop-auto=no

[svp]
input-ipc-server=/tmp/mpvsocket
hr-seek-framedrop=no
watch-later-options-remove=vf
interpolation=no
video-sync=audio
hwdec=auto
