# Keep open and don't autoplay
keep-open=always

# Automatically open all the files in the same dir
autocreate-playlist=same

# Volume
volume=50
volume-max=150

# Misc
demuxer-max-bytes=8GiB
hr-seek=yes
cache=yes
cache-pause=no

# GPU Acceeleration
profile=gpu-hq
hwdec=auto
hwdec-codecs=all
gpu-context=waylandvk
vd-lavc-dr=yes
vd-lavc-threads=8
opengl-pbo=yes

# Scaling
scale=ewa_lanczos
cscale=ewa_lanczos
dscale=mitchell
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes

# Interpolation
video-sync=display-resample
interpolation
tscale=oversample

# Debanding
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=20
deband-grain=8

# Color
target-colorspace-hint=yes
gamut-mapping-mode=clip

# Dithering
dither-depth=auto
temporal-dither=yes
dither=fruit

# Autocrop
script-opts-append=autocrop-auto=no

[svp]
input-ipc-server=/tmp/mpvsocket
hr-seek-framedrop=no
watch-later-options-remove=vf
interpolation=no
video-sync=audio
hwdec=auto
