pulse.rules = [
    {
        matches = [
            { application.process.binary = "!~^(pavucontrol|pactl|hyprpwcenter)$" }
        ]
        actions = {
            quirks = [ block-source-volume ]
        }
    }
]
