alias = "ricer"
default_color_format = "hex"
rgba01_precision = 2
replace_files = true
create_example = false
color_log_format = "Name: {name} | HEXA: {hexa} | RGBA: {rgba} | RGBA01: {rgba01}"
file_log_format = "Name: {name}\nPath: {path}\nTarget Path: {target_path}\nFormat: {format}"
space_colors = false
space_files = true

[Values]
terminal = "alacritty"
bg = "~/.config/Backgrounds/CatppuccinCityLandscape.png"
font = "Cascadia Code NF"
min_font_size = 8
small_font_size = 11
font_size = 13
big_font_size = 15
max_font_size = 30
icons = "Nordzy-dark"
cursor = "Nordzy-catppuccin-macchiato-blue"
cursor_size = 30
outline_size = 2
rounding = 10
gtk_theme = "catppuccin-macchiato-blue-standard+default"
nvim_theme = "catppuccin-macchiato"
notification_duration = 3

highlight_hsv = "h+0.s+0.v+10"
placeholder_hsv = "h+0.s+0.v-10"
inactive_hsv = "h+0.s+0.v-15"
disabled_hsv = "h+0.s-5.v-15"

[Colors]
black = "181926"
red = "ed8796"
green = "a6da95"
yellow = "f5a97f"
blue = "8aadf4"
magenta = "c6a0f6"
cyan = "7dc4e4"
white = "b7bdf8"

br_black = "$black.$highlight_hsv"
br_red = "$red.$highlight_hsv"
br_green = "$green.$highlight_hsv"
br_yellow = "$yellow.$highlight_hsv"
br_blue = "$blue.$highlight_hsv"
br_magenta = "$magenta.$highlight_hsv"
br_cyan = "$cyan.$highlight_hsv"
br_white = "$white.$highlight_hsv"

foreground = "$white"
foreground_highlight = "$foreground.$highlight_hsv"
foreground_placeholder = "$foreground.$placeholder_hsv"
foreground_inactive = "$foreground.$inactive_hsv"
foreground_disabled = "$foreground.$disabled_hsv"

foreground_alt = "$blue"
foreground_highlight_alt = "$foreground_alt.$highlight_hsv"
foreground_placeholder_alt = "$foreground_alt.$placeholder_hsv"
foreground_inactive_alt = "$foreground_alt.$inactive_hsv"
foreground_disabled_alt = "$foreground_alt.$disabled_hsv"

background = "$black"
background_highlight = "$background.$highlight_hsv"
background_inactive = "$background.$inactive_hsv"
background_disabled = "$background.$disabled_hsv"

background_alt = "$br_black"
background_highlight_alt = "$background_alt.$highlight_hsv"
background_inactive_alt = "$background_alt.$inactive_hsv"
background_disabled_alt = "$background_alt.$disabled_hsv"

button = "$br_black"
button_highlight = "$button.$highlight_hsv"
button_inactive = "$button.$inactive_hsv"
button_disabled = "$button.$disabled_hsv"

button_text = "$blue"
button_text_highlight = "$button_text.$highlight_hsv"
button_text_inactive = "$button_text.$inactive_hsv"
button_text_disabled = "$button_text.$disabled_hsv"

outline = "$blue"
outline_alt = "$br_white"
outline_inactive = "$outline.v-50"
outline_inactive_alt = "$outline_alt.v-50"

shadow = "$black"
shadow_inactive = "$shadow.$inactive_hsv"

link = "$cyan"
link_visited = "$blue"

visualizer = "$white"
visualizer_outline = "$blue"

[Files]
Hyprland = "~/.config/hypr/hyprland.conf"
Alacritty = "~/.config/alacritty.toml"
NvimTheme = "~/.config/nvim/lua/theme.lua"
RofiConfig = "~/.config/rofi/config.rasi"
RofiTheme = "~/.config/rofi/themes/theme.rasi"
GLavaRadial = "~/.config/glava/radial.glsl"
GTKSettings = "~/.local/share/nwg-look/gsettings"
Dunst = "~/.config/dunst/dunstrc"
Fonts = "~/.config/fontconfig/fonts.conf"
Hyprmouse = "~/.config/hypr/hyprmouse.conf"
QtCol = "~/.config/qt5ct/colors/theme.conf"
QtColors = "~/.config/qt6ct/colors/theme.conf"
KDEGlobals = "~/.config/kdeglobals"
FirefoxTheme = "~/.config/FirefoxTheme/manifest.json"
YTEnhancer = "~/.config/YouTubeEnhancer.json"
Kitty = "~/.config/kitty/kitty.conf"
