alias = "ricer"
default_color_format = "hex"
rgba01_precision = 2
replace_files = true
color_log_format = "Name: {name} | HEXA: {hexa} | RGBA: {rgba} | RGBA01: {rgba01}"
file_log_format = "Name: {name}\nPath: {path}\nTarget Path: {target_path}\nFormat: {format}\n"

[Values]
bg = "CatppuccinRuinsInASnowyBlizzard.png"
font = "Cascadia Code NF"
font_size = 13
icons = "Nordzy-dark"
cursor = "Nordzy-cursors-white"
cursor_size = 30
outline_size = 2
border_radius = 10
nvim_theme = "catppuccin-macchiato"

[Colors]
black = "181926"
red = "ed8796"
green = "a6da95"
yellow = "f5a97f"
blue = "8aadf4"
magenta = "c6a0f6"
cyan = "7dc4e4"
white = "939ab7"

br_black = "24273a"
br_red = "ee99a0"
br_green = "8bd5ca"
br_yellow = "eed49f"
br_blue = "b7bdf8"
br_magenta = "f5bde6"
br_cyan = "91d7e3"
br_white = "cad3f5"

text = "cad3f5"
text_link = "8aadf4"
text_highlight = "b7bdf8"
text_inactive = "a5adcb"
text_placeholder = "b8c0e0"

background = "24273a"
background_alt = "24273a"
background_inactive = "5b6078"
background_inactive_alt = "5b6078"

outline = "b7bdf8"
outline_alt = "8aadf4"
outline_inactive = "24273a"
outline_inactive_alt = "5b6078"

shadow = "181926"

[Files]
Hyprland = ["~/.config/hypr/hyprland.conf", "hex"]
Alacritty = ["~/.config/alacritty.toml", "hex"]
NvimTheme = "~/.config/nvim/lua/theme.lua"
