alias = "ricer"
default_format = "hex"
color_log_format = "Name: {name} | HEXA: {hexa} | RGBA: {rgba} | RGBA01: {rgba01}"
file_log_format = "Name: {name}\nPath: {path}\nTarget Path: {target_path}\nFormat: {format}\n"
rgba01_precision = 2
replace_files = true

[Values]
bg = "NordicRuinsInASnowyBlizzard.jpg"
font = "Cascadia Code NF"
font_size = 13
icons = "Nordzy-dark"
cursor = "Nordzy-cursors-white"
cursor_size = 30
outline_size = 2
border_radius = 10
nvim_theme = "nord"

[Colors]
black = "2e3440"
red = "bf616a"
green = "a3be8c"
yellow = "ebcb8b"
blue = "5e81ac"
magenta = "b48ead"
cyan = "88c0d0"
white = "d8dee9"

br_black = "3b4252"
br_red = "d08770"
br_green = "a3be8c"
br_yellow = "ebcb8b"
br_blue = "81a1c1"
br_magenta = "b48ead"
br_cyan = "8fbcbb"
br_white = "eceff4"

text = "eceff4"
text_link = "81a1c1"
text_highlight = "88c0d0"
text_inactive = "d8dee9"
text_placeholder = "4c566a"

background = "2e3440"
background_alt = "2e3440"
background_inactive = "4c566a"
background_inactive_alt = "4c566a"

outline = "eceff4"
outline_alt = "81a1c1"
outline_inactive = "2e3440"
outline_inactive_alt = "4c566a"

shadow = "2e34401a"
shadow_inactive = "2e34401a"

[Files]
Hyprland = ["~/.config/hypr/hyprland.conf", "hex"]
Alacritty = ["~/.config/alacritty.toml", "hex"]
NvimTheme = ["~/.config/nvim/lua/theme.lua"]
