alias = "ricer"
default_color_format = "hex"
rgba01_precision = 2
replace_files = true
create_example = false
color_log_format = "Name: {name} | HEXA: {hexa} | RGBA: {rgba} | RGBA01: {rgba01}"
file_log_format = "Name: {name}\nPath: {path}\nTarget Path: {target_path}\nFormat: {format}"
space_colors = false
space_files = true

[Values]
terminal = "alacritty"
bg = "NordicRuinsInASnowyBlizzard.jpg"
font = "Cascadia Code NF"
min_font_size = 8
small_font_size = 11
font_size = 13
big_font_size = 15
max_font_size = 30
icons = "Nordzy-dark"
cursor = "Nordzy-cursors-white"
cursor_size = 30
outline_size = 2
rounding = 10
gtk_theme = "Nordic-darker-v40"
nvim_theme = "nord"
notification_duration = 3

[Colors]
black = "2e3440"
red = "bf616a"
green = "a3be8c"
yellow = "ebcb8b"
blue = "5e81ac"
magenta = "b48ead"
cyan = "88c0d0"
white = "d8dee9"

br_black = "3b4252"
br_red = "d08770"
br_green = "a3be8c"
br_yellow = "ebcb8b"
br_blue = "81a1c1"
br_magenta = "b48ead"
br_cyan = "8fbcbb"
br_white = "eceff4"

text = "eceff4"
text_highlight = "81a1c1"
text_inactive = "d8dee9"
text_placeholder = "4c566a"
link = "88c0d0"
link_visited = "5e81ac"

background = "2e3440"
background_alt = "2e3440"
background_highlight = "4c566a"
background_highlight_alt = "4c566a"
background_inactive = "4c566a"
background_inactive_alt = "4c566a"

outline = "81a1c1"
outline_alt = "eceff4"
outline_inactive = "2e3440"
outline_inactive_alt = "4c566a"

shadow = "2e34401a"
shadow_inactive = "2e34401a"

button = "3b4252"
button_inactive = "434c5e"

[Files]
Hyprland = "~/.config/hypr/hyprland.conf"
Alacritty = "~/.config/alacritty.toml"
NvimTheme = "~/.config/nvim/lua/theme.lua"
RofiConfig = "~/.config/rofi/config.rasi"
RofiTheme = "~/.config/rofi/themes/theme.rasi"
GLavaRadial = "~/.config/glava/radial.glsl"
GTKSettings = "~/.local/share/nwg-look/gsettings"
Dunst = "~/.config/dunst/dunstrc"
Fonts = "~/.config/fontconfig/fonts.conf"
Hyprmouse = "~/.config/hypr/hyprmouse.conf"
QtCol = "~/.config/qt5ct/colors/theme.conf"
QtColors = "~/.config/qt6ct/colors/theme.conf"
KDEGlobals = "~/.config/kdeglobals"
