decoration {
    # Rounding
    rounding = $rounding
    rounding_power = $roundingPower

    # Opacity
    active_opacity = $activeOpacity
    inactive_opacity = $inactiveOpacity

    # Dimming
    dim_modal = true
    dim_inactive = true
    dim_strength = 0.2
    dim_special = 0.2
    dim_around = 0.4


    blur {
        enabled = $blur
        size = $blurSize
        passes = $blurPasses
        ignore_opacity = true
        new_optimizations = false # Fixes hyprwinwrap not being visible behind tiled windows
        xray = false
        noise = 0.02
        contrast = 1
        brightness = 0.6
        vibrancy = 1
        vibrancy_darkness = 0
        special = false # Set this to true if conflict with hyprwinwrap gets resolved
        popups = true
        popups_ignorealpha = 0.2
        input_methods = true
        input_methods_ignorealpha = 0.01
    }

    shadow {
        enabled = true
        range = 4
        render_power = 3
        sharp = false
        ignore_window = true
        color = $shadowCol
        color_inactive = $shadowInactiveCol
        offset = 0, 0
        scale = 1
    }
}

