decoration {
	# Rounding
	rounding = $rounding
	rounding_power = $roundingPower
	inactive_opacity = $inactiveOpacity

	# Opacity
	active_opacity = $activeOpacity
	inactive_opacity = $inactiveOpacity

	blur {
		enabled = $blur
		xray = false
		size = $blurSize
		passes = $blurPasses
		ignore_opacity = true
		new_optimizations = false # Fixes hyprwinwrap not being visible behind tiled windows
		noise = 0.02
		contrast = 1
		brightness = 0.6
		vibrancy = 1
		special = false # Set this to true if conflict with hyprwinwrap gets resolved
		popups = true
		input_methods = true
	}

	shadow {
		enabled = false
		range = 10
		render_power = 2
		color = $shadowCol
		color_inactive = $shadowInactiveCol
	}
}

