general {
    border_size = $borderSize
    col.active_border = $borderActiveCol
    col.inactive_border = $borderInactiveCol
    layout = dwindle
    resize_on_border = true
    gaps_in = 5
    gaps_out = 10
	
	snap {
		enabled = true
		window_gap = 25
		monitor_gap = 25
	}
}

