general {
    gaps_in = $gapsIn
    gaps_out = $gapsOut

    border_size = $borderSize
    col.active_border = $borderActiveCol
    col.inactive_border = $borderInactiveCol
    resize_on_border = true

    layout = scrolling
    extend_border_grab_area = 0 # This messes up selection in tiled windows when not 0
    allow_tearing = true

    snap {
        enabled = true
        window_gap = 10
        monitor_gap = 10
    }
}

$isMaster = [[ $(hyprctl -j getoption general:layout | jq -r .str) == "master" ]]
$isDwindle = [[ $(hyprctl -j getoption general:layout | jq -r .str) == "dwindle" ]]
$isScrolling = [[ $(hyprctl -j getoption general:layout | jq -r .str) == "scrolling" ]]
