group {
	col.border_active = $groupBorder
	col.border_inactive = $groupBorderInactive
	col.border_locked_active = $groupBorderLocked
	col.border_locked_inactive = $groupBorderLockedInactive

	groupbar {
		enabled = false
	}
}

