# MainMod
$mainMod = SUPER

# Apps
$terminal = kitty
$browser = firefox
$textEditor = nvim
$fileManager = dolphin

# Window
$activeOpacity = 0.85
$inactiveOpacity = 0.9
$rounding = 10
$borderSize = 2
$borderActiveCol = rgba(6699CCFF) rgba(BDDFFFFF) 90deg
$borderInactiveCol = rgba(26394CFF) rgba(5E6E7FFF) 90deg
$shadowCol = rgba(102840FF)
$shadowInactiveCol = rgba(061019FF)

# Font
$font = Courier Prime Code
$fontSize = 15

# Theme
$theme = Ricer
$background = ~/.config/Backgrounds/Nord/NordicRuinsInASnowyBlizzard.jpg
$bgCol = 102840
$fgCol = ACCAE6
$bgColA = 102840FF
$termColors = LS_COLORS,di=#BDDFFF:fi=#ACCAE6:ln=#6699CC:pi=#275E99:so=#275E99:bd=#275E99:cd=#275E99:or=#174066:mi=#174066:ex=#1F4F7F

# Cursor
$cursor = Bibata-Modern-Ice
$cursorSize = 32
$cursorRot = 21

# Animation
$animationDuration = 4
$animationCurve = overshoot

# Group
$groupBorder = rgba(6699CCFF) rgba(BDDFFFFF) 90deg
$groupBorderInactive = rgba(26394CFF) rgba(5E6E7FFF) 270deg
$groupBorderLocked = rgba(205080FF)
$groupBorderLockedInactive = rgba(26394CFF)


# Source Configs
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/UnityFix.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/group.conf
source = ~/.config/hypr/startup.conf

# Reload hyprpm and source the plugins config
exec-once = hyprpm reload -nn
source = ~/.config/hypr/plugins.conf
exec-once = sleep 5

# This is needed for shaders using time, delete this line to potentially improve performance
#debug:damage_tracking = off

