require("hyprland.env")
require("hyprland.rules")

require("hyprland.animations")
require("hyprland.binds")
require("hyprland.decoration")
require("hyprland.input")
require("hyprland.layouts")
require("hyprland.ecosystem")
require("hyprland.gamemode")
require("hyprland.general")
require("hyprland.misc")
require("hyprland.monitors")
require("hyprland.render")
require("hyprland.startup")
