$font = Maple Mono NF CN

general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    path = screenshot
    color = rgba(0, 0, 0, 1)
    blur_passes = 4
    blur_size = 20
    noise = 0.02
    brightness = 0.9
}

# Time
label {
    text = cmd[update:1000] echo "<span foreground='##ffffff'>$(date +"%T")</span>"
    color = rgba(1, 1, 1, 1)
    font_size = 32
    font_family = $font
    halign = center
    valign = center
    position = 0, 150
}

# Date
label {
    text = cmd[update:1000] echo "<span foreground='##ffffff'>$(date +"%d/%m/%Y")</span>"
    color = rgba(1, 1, 1, 1)
    font_size = 32
    font_family = $font

    halign = center
    valign = center
    position = 0, 100
}

# Day
label {
    text = cmd[update:1000] echo "<span foreground='##ffffff'>$(date +"%A")</span>"
    color = rgba(1, 1, 1, 1)
    font_size = 32
    font_family = $font

    halign = center
    valign = center
    position = 0, 50
}

input-field {
    size = 500, 100
    halign = center
    valign = center
    position = 0, -50
    outline_thickness = 2
    fail_transition = 300
    invert_numlock = true

    outer_color = rgba(255, 255, 255, 0.75)
    inner_color = rgba(0, 0, 0, 0.1)
    font_color = rgba(255, 255, 255, 1.0)
    check_color = rgba(255, 255, 255, 1.0)
    fail_color = rgba(255, 0, 0, 1.0)
    capslock_color = rgba(0, 255, 0, 1.0)
    numlock_color = rgba(0, 255, 255, 1.0)
    bothlock_color = rgba(255, 0, 255, 1.0)

    placeholder_text = <i>Password</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
}
