background = rgba(4C5843FF)
base = rgba(4C5843FF)
text = rgba(D8DED3FF)
alternate_base = rgba(3E4637FF)
bright_text = rgba(F1F7EBFF)
accent = rgba(F1F7EBFF)
accent_secondary = rgba(F1F7EBFF)
h1_size = 25
h2_size = 16
h3_size = 13
font_size = 11
small_font_size = 9
icon_theme = "Ricer"
