background = rgba(081D26FF)
base = rgba(081D26FF)
text = rgba(A3C5CCFF)
alternate_base = rgba(0C2E3FFF)
bright_text = rgba(B7DCE5FF)
accent = rgba(B7DCE5FF)
accent_secondary = rgba(B7DCE5FF)
h1_size = 25
h2_size = 16
h3_size = 13
font_size = 11
small_font_size = 9
icon_theme = "Ricer"
