# MainMod
$mainMod = SUPER

# Apps
$terminal = kitty
$browser = zen-browser
$textEditor = nvim
$fileManager = dolphin

# Window
$activeOpacity = 0.85
$inactiveOpacity = 0.9
$rounding = 15
$roundingPower = 4
$borderSize = 2
$borderActiveCol = rgba(608FBFFF) rgba(BDDFFFFF) 90deg
$borderInactiveCol = rgba(202F3FFF) rgba(5E6E7FFF) 90deg
$shadowCol = rgba(102840FF)
$shadowInactiveCol = rgba(061019FF)

# Font
$font = Courier Prime Code
$fontSize = 15

# Theme
$theme = Ricer
$background = ~/.config/Backgrounds/Nord/NordicRuinsInASnowyBlizzard.jpg
$bgCol = 102840
$fgCol = ACCAE6
$bgColA = 102840FF
$termColors = LS_COLORS,di=#608FBF:fi=#ACCAE6:ln=#6DA1D8:pi=#6DA1D8:so=#3687D8:bd=#3687D8:cd=#3687D8:or=#D83636:mi=#D83636:ex=#6DD836

# Cursor
$cursor = Bibata-Modern-Ice
$cursorSize = 32
$cursorRot = 21

# Animation
$animationDuration = 4
$animationCurve = overshoot

# Group
$groupBorder = rgba(608FBFFF) rgba(BDDFFFFF) 90deg
$groupBorderInactive = rgba(202F3FFF) rgba(5E6E7FFF) 270deg
$groupBorderLocked = rgba(BFA730FF)
$groupBorderLockedInactive = rgba(202F3FFF)


# Source Configs
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/HyprlandUnityFix/UnityFix.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/group.conf
source = ~/.config/hypr/startup.conf

# Reload hyprpm and source the plugins config
exec-once = hyprpm reload -nn
source = ~/.config/hypr/plugins.conf
exec-once = sleep 5

# This is needed for shaders using time, delete this line to potentially improve performance
#debug:damage_tracking = off
