# MainMod
$mainMod = SUPER

# Apps
$terminal = ghostty
$terminal_command = ghostty +new-window
$browser = zen-browser
$textEditor = nvim
$fileManager = dolphin

# Window
$activeOpacity = 0.85
$inactiveOpacity = 0.75
$rounding = 10
$roundingPower = 4
$borderSize = 2
$borderRotation = 90deg
$borderFadeAnimation = 1
$borderFadeDuration = 1
$borderFadeBezier = quadOut
$borderRotationAnimation = 1
$borderRotationDuration = 30
$borderRotationBezier = linear
$borderRotationType = loop
$borderActiveCol = rgba(BDDFFFFF) rgba(3687D8FF) $borderRotation
$borderInactiveCol = rgba(ABBBCCFF) rgba(396FA5FF) $borderRotation
$gapsIn = 2
$gapsOut = 4
$blur = true
$blurSize = 20
$blurPasses = 4
$shadowCol = rgba(102840FF)
$shadowInactiveCol = rgba(061019FF)

# Font
$font = Maple Mono NF CN
$fontSize = 9

# Theme
$theme = oomox-Ricer
$background = ~/.config/Backgrounds/Frost/FrostedPalace.png
$bgCol = 102840
$fgCol = ACCAE6
$bgColA = 10284010
$termColors = LS_COLORS,di=#608FBF:fi=#ACCAE6:ln=#6DA1D8:pi=#6DA1D8:so=#3687D8:bd=#3687D8:cd=#3687D8:or=#D83636:mi=#D83636:ex=#6DD836

# Cursor
$cursor = Bibata-Modern-Ice
$cursorSize = 24
$cursorRot = 21

# Animation
$animationDuration = 4
$animationCurve = overshoot
bezier = myBezier, 0.05, 0.9, 0.1, 1.05
bezier = linear, 0.0, 0.0, 1.0, 1.0
bezier = quad, 0.45, 0, 0.55, 1
bezier = quadOut, 0.5, 1, 0.89, 1
bezier = expo, 0.87, 0, 0.13, 1
bezier = expoIn, 0.7, 0, 0.84, 0
bezier = expoOut, 0.16, 1, 0.3, 1
bezier = overshoot, 0.25, 1.75, 0, 0.9

# Group
$groupBorder = rgba(BDDFFFFF) rgba(3687D8FF) 90deg
$groupBorderInactive = rgba(A0BCD8FF) rgba(2C6FB2FF) 270deg
$groupBorderLocked = rgba(BFA730FF)
$groupBorderLockedInactive = rgba(A0BCD8FF)


# Source Configs
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/render.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/HyprlandUnityFix/UnityFix.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/ecosystem.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/group.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/plugins.conf
exec-once = sleep 5

# This is needed for shaders using time, delete this line to potentially improve performance
#debug:damage_tracking = off
