background = rgba(10284010)
base = rgba(10284020)
text = rgba(ACCAE6FF)
alternate_base = rgba(15395920)
bright_text = rgba(BDDFFFFF)
accent = rgba(6DA1D8FF)
accent_secondary = rgba(BDDFFFFF)
h1_size = 15
h2_size = 11
h3_size = 9
font_size = 6
small_font_size = 4
icon_theme = "Ricer"
