input {
    kb_layout = us
    kb_variant = 
    kb_model =
    kb_options = #caps:swapescape
    kb_rules =
    repeat_delay = 400
    numlock_by_default = true

    follow_mouse = 1

    #scroll_method = on_button_down
    scroll_factor = 0.5
    
    touchpad {
	natural_scroll = false
    }

    sensitivity = 0
    accel_profile = flat
}

