input {
    kb_layout = us, ru, rs,   rs
    kb_variant =  ,   , latin,
    kb_model =
    kb_options = #caps:swapescape
    kb_rules =
    repeat_delay = 300
    numlock_by_default = true

    follow_mouse = 1

    #scroll_method = on_button_down
    scroll_factor = 0.5
    
    touchpad {
	natural_scroll = false
    }

    sensitivity = 0
    accel_profile = flat

	focus_on_close = 1

	#kb_options = caps:swapescape
}

