input {
    # Keyboard
    kb_model =
    kb_layout = us, ru, rs,    rs
    kb_variant =  ,   , latin,
    kb_options = #caps:swapescape
    kb_rules =
    numlock_by_default = false
    repeat_rate = 25
    repeat_delay = 300

    # Mouse
    sensitivity = 0
    accel_profile = flat
    left_handed = false
    scroll_factor = 1
    follow_mouse = 1

    touchpad {
        disable_while_typing = false
        natural_scroll = false
    }

    focus_on_close = 1

    #kb_options = caps:swapescape
}
