misc {
    middle_click_paste = false
    disable_hyprland_logo = true
    disable_splash_rendering = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    background_color = rgb($bgCol)
    font_family = $font
	splash_font_family = $font
	close_special_on_empty = false
}

