misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    font_family = $font
	splash_font_family = $font
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
	focus_on_activate = false
    background_color = rgb($bgCol)
	close_special_on_empty = false
    middle_click_paste = false
	anr_missed_pings = 5
}

