monitorv2 {
    output =
    mode = highres@highrr
    position = 0x0
    scale = 1
    bitdepth = 10
}

#monitorv2 {
#   output = SUNSHINE
#   mode = 2560x1440@60
#   position = 5120x1440
#   scale = 1
#   bitdepth = 10
#}
#exec-once = hyprctl output create headless SUNSHINE
