monitor = , 5120x1440@240, auto, auto
monitor = HDMI-A-2, disable
#monitor = , 2560x1440@120, 0x0, auto
#monitor = HDMI-A-2, 2560x1440@120, 2560x0, auto

#hyprlang noerror true
experimental:xx_color_management_v4 = true
experimental:wide_color_gamut = true
#hyprlang noerror false
