permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

# Hyprchroma
#hyprlang noerror true
windowrulev2 = plugin:chromakey,fullscreen:0
chromakey_background = 7,8,17
#hyprlang noerror false

plugin {
    csgo-vulkan-fix {
        res_w = 1280
        res_h = 1024
        class = cs2
        #class = csgo_linux64
        #class = steam_app_730 # Classic Counter/Classic Offensive
    }

    hyprwinwrap {
        #class = GLava
        class = Nisualizer.x86_64
        #class = Background
    }

    dynamic-cursors {
        enabled = true
        mode = rotate
        threshold = 1
        rotate:length = $cursorSize
        tilt:limit = 3000
        stretch:limit = 3000
        shake:enabled = false
        shake:effects = true
        shaperule = default, rotate, rotate:offset: $cursorRot
    }

    hyprexpo {
       columns = 3
       gap_size = 2
       bgCol = rgb($fgCol)
       workspace_method = first 1

       enable_gesture = true # laptop touchpad, 4 fingers
       gesture_distance = 300 # how far is the "max"
       gesture_positive = true # positive = swipe down. Negative = swipe up.
    }

    hyprscrolling {
        fullscreen_on_one_column = false
    }

    hyprtrails {
    	color = rgba(ECEFF4FF)
    }
    
    hyprbars {
        bar_height = 25
    	col.text = rgb(ECEFF4)
    	bar_text_font = $font $fontSize
    	bar_padding = 10
    	bar_button_padding = 10
        hyprbars-button = rgb(BF616A), 10, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(81A1C1), 10, , hyprctl dispatch fullscreen 1
    }

    hyprtasking {
        layout = grid

        gap_size = 10
        bg_color = 0x$bgCol
        border_size = $borderSize
        exit_behavior = hovered

        gestures {
            enabled = true
            open_fingers = 3
            open_distance = 300
            open_positive = true
        }

        grid {
            rows = 3
            cols = 3
        }

        linear {
            height = 400
            scroll_speed = 1.1
            blur = 0
        }
    }

    #hyprlang noerror true
    hyprfocus {
        mode = slide
        fade_opacity = 0.9
        bounce_strength = 0.99
        slide_height = 10
        animation = hyprfocusIn, 1, 0.75, expoOut
        animation = hyprfocusOut, 1, 0.75, expoOut
    }
    #hyprlang noerror false
}
