permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

# Hyprchroma
#hyprlang noerror true
windowrulev2 = plugin:chromakey,fullscreen:0
chromakey_background = 7,8,17
#hyprlang noerror false

plugin {
    hyprwinwrap {
        #class = GLava
        class = Nisualizer.x86_64
        #class = Background
    }

    hyprtrails {
    	color = rgba(ECEFF4FF)
    }
    
    hyprbars {
        bar_height = 25
    	col.text = rgb(ECEFF4)
    	bar_text_font = $font $fontSize
    	bar_padding = 10
    	bar_button_padding = 10
        hyprbars-button = rgb(BF616A), 10, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(81A1C1), 10, , hyprctl dispatch fullscreen 1
    }
    
    csgo-vulkan-fix {

        res_w = 1280
        res_h = 1024
        class = csgo_linux64
        
        res_w = 1280
        res_h = 1024
        class = cs2
    }

    hyprexpo {
       columns = 3
       gap_size = 2
       bgCol = rgb($fgCol)
       workspace_method = first 1

       enable_gesture = true # laptop touchpad, 4 fingers
       gesture_distance = 300 # how far is the "max"
       gesture_positive = true # positive = swipe down. Negative = swipe up.
    }

    hyprtasking {
        layout = grid

        gap_size = 10
        bg_color = 0x$bgCol
        border_size = $borderSize
        exit_behavior = hovered

        gestures {
            enabled = true
            open_fingers = 3
            open_distance = 300
            open_positive = true
        }

        grid {
            rows = 3
            cols = 3
        }

        linear {
            height = 400
            scroll_speed = 1.1
            blur = 0
        }
    }

    dynamic-cursors {
        enabled = true
        mode = rotate
        threshold = 1
        rotate:length = $cursorSize
        tilt:limit = 3000
        stretch:limit = 3000
        shake:enabled = false
        shake:effects = true
        shaperule = default, rotate, rotate:offset: $cursorRot
    }

    hyprfocus {
        enabled = yes
        animate_floating = yes
        animate_workspacechange = yes
        focus_animation = shrink
        bezier = realsmooth, 0.28,0.29,.69,1.08
        shrink {
            shrink_percentage = 0.9975
            in_bezier = realsmooth
            in_speed = 1
            out_bezier = realsmooth
            out_speed = 2
        }
    }
}
