permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

source = ~/.config/hypr/plugins/csgo-vulkan-fix.conf
source = ~/.config/hypr/plugins/dynamic-cursors.conf
source = ~/.config/hypr/plugins/hyprbars.conf
source = ~/.config/hypr/plugins/hyprexpo.conf
source = ~/.config/hypr/plugins/hyprfocus.conf
source = ~/.config/hypr/plugins/hyprscrolling.conf
source = ~/.config/hypr/plugins/hyprtasking.conf
source = ~/.config/hypr/plugins/hyprtrails.conf
source = ~/.config/hypr/plugins/hyprwinwrap.conf
source = ~/.config/hypr/plugins/hyprchroma.conf
