# Prevents windows from maximizing themeselves
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = suppressevent maximize fullscreen,class:^(cs2)$

# Transparency
windowrulev2 = opacity $activeOpacity, class:^(.*)$
windowrulev2 = opacity 1, class:^(vlc)(.*)$ 
windowrulev2 = opacity 1, class:^(mpv)(.*)$ 
windowrulev2 = opacity 1, title:^(Grayjay)(.*)$ 
windowrulev2 = opacity 1, class:^(FreeTube)(.*)$ 

# Ncmpcpp
windowrulev2 = workspace special silent, class:(Ncmpcpp)

# Nisualizer
windowrule = minsize 5120 1440, ^(Nisualizer.x86_64)$
windowrule = nofocus, ^(Nisualizer.x86_64)$
windowrule = opacity 1, ^(Nisualizer.x86_64)$

# GLava
windowrule = noblur, ^(GLava)$

# Alacritty
#windowrulev2 = tile, class:^(Alacritty)(.*)$ #Needed for alacritty-smooth-cursor because it's running under xwayland

# Jetbrains
windowrulev2 = nofocus, class:^(jetbrains)(.*)$, title:^(win)(.*)$ #Prevents tooltips from stealing focus

# Telegram
windowrulev2 = workspace 2 silent, class:(org.telegram.desktop)

# Nheko
windowrulev2 = workspace 2 silent, class:(nheko)

# Vesktop
windowrulev2 = workspace 2 silent, class:(vesktop)
windowrulev2 = tile, class:(vesktop) #Had a bug where vesktop was starting in fullscreen, might not be needed anymore

# Obsidian
windowrulev2 = workspace 9 silent, class:(obsidian) #Always opens obsidian on 5th workspace
windowrulev2 = tile, class:(obsidian) #Prevents it from being fullscreen on launch

# KeepassXC
windowrulev2 = workspace 10 silent, initialTitle:(.*\[Locked\] - KeePassXC)

# Clipse
windowrulev2 = float, title:(clipse)

# Dunst
layerrule = blur, notifications
layerrule = ignorealpha 0, notifications
layerrule = animation slide, notifications

# Rofi
layerrule = blur, rofi
layerrule = ignorealpha 0, rofi
layerrule = animation slide, rofi

# SwayNC
layerrule = blur, swaync-control-center
layerrule = ignorealpha 0, swaync-control-center
layerrule = blur, swaync-notification-window

# Transitioner
layerrule = noanim, Transitioner

# Slurp(fixes screenshots being white)
layerrule = noanim, selection

# XWaylandBridge
windowrulev2 = opacity 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2 = noblur,class:^(xwaylandvideobridge)$
