# Prevents windows from maximizing themeselves
windowrule = suppressevent maximize, class:.*
windowrule = suppressevent maximize fullscreen,class:^(cs2)$
windowrule = suppressevent maximize fullscreen,class:^(steam_app_730)$

# Transparency
windowrule = opaque, class:^(vlc)(.*)$ 
windowrule = opaque, class:^(mpv)(.*)$ 
windowrule = opaque, class:^(viewnior)(.*)$ 
windowrule = opaque, class:^(krita)(.*)$ 
windowrule = opaque, class:^(kdenlive)(.*)$ 
windowrule = opaque, class:^(org.kde.kdenlive)(.*)$ 
windowrule = opaque, class:^(blender)(.*)$ 
windowrule = opaque, title:^(Grayjay)(.*)$ 
windowrule = opaque, class:^(FreeTube)(.*)$ 
windowrule = opaque, class:^(zen)(.*)$ 
windowrule = opaque, class:^(blur-Linux-Release-x64)(.*)$ 

# CS2
windowrulev2 = immediate, class:^(cs2)$
windowrulev2 = immediate, class:^(steam_app_730)$

# Ncmpcpp
windowrule = workspace special silent, class:(Ncmpcpp)

# Nisualizer
windowrule = minsize 5120 1440, class:^(Nisualizer.x86_64)$
windowrule = nofocus, class:^(Nisualizer.x86_64)$
windowrule = opaque, class:^(Nisualizer.x86_64)$

# GLava
windowrule = noblur, class:^(GLava)$

# Alacritty
#windowrule = tile, class:^(Alacritty)(.*)$ # Needed for alacritty-smooth-cursor because it's running under xwayland

# Jetbrains
windowrule = nofocus, class:^(jetbrains)(.*)$, title:^(win)(.*)$ # Prevents tooltips from stealing focus

# Telegram
windowrule = workspace 2 silent, class:(org.telegram.desktop)

# Nheko
windowrule = workspace 2 silent, class:(nheko)

# Vesktop
windowrule = workspace 2 silent, class:(vesktop)

# Equibop
windowrule = workspace 2 silent, class:(equibop)

# Obsidian
windowrule = workspace 9 silent, class:(obsidian)
windowrule = tile, class:(obsidian) # Prevents it from being fullscreen on launch

# KeepassXC
windowrule = workspace 10 silent, initialTitle:(.*\[Locked\] - KeePassXC)

# OBS
windowrule = workspace 10 silent, initialClass:(com.obsproject.Studio)

# Clipse
windowrule = float, title:(clipse)

# Unity
windowrule = opaque, class:(Unity), initialTitle:^(Unity - Unity.*)$

# Flax
windowrule = opaque, initialTitle:^(Flax Editor.*)$

# Material Maker
windowrule = tile, class:(Material Maker), initialTitle:(Godot)
windowrule = opaque, class:(Material Maker), initialTitle:(Godot)
windowrule = float, class:(Material Maker), title:(Alert!)

# DaVinci Resolve
windowrule = opaque, class:(resolve), title:^(DaVinci Resolve.*)$

# Dunst
layerrule = blur, notifications
layerrule = ignorealpha 0, notifications
layerrule = animation slide, notifications

# Rofi
layerrule = blur, rofi
layerrule = ignorealpha 0, rofi
layerrule = animation slide, rofi

# SwayNC
layerrule = blur, swaync-control-center
layerrule = ignorealpha 0, swaync-control-center
layerrule = blur, swaync-notification-window

# Transitioner
layerrule = noanim, Transitioner

# Slurp(fixes screenshots being white)
layerrule = noanim, selection

# Hints
layerrule = noanim, hints

# XWaylandBridge
windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$
