# Startup
# Exports env vars to services and fixes long app launch times
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY
exec-once = hyprlock
exec-once = sunshine

# App Tracking
exec-once = fish -c "track_app_usage"

# Settings
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprctl setcursor $cursor $cursorSize

# Daemons
exec-once = pypr
exec-once = dunst
exec-once = hypridle
exec-once = syncthing
exec-once = kdeconnectd
exec-once = kdeconnect-indicator
#exec-once = ollama serve
exec-once = ydotoold # required for Hyprmouse
exec-once = sleep 3 && lan-mouse daemon
#exec-once = easyeffects --gapplication-service
exec-once = openrgb --startminimized --profile "Off" --server
exec-once = vicinae server

# Background
exec-once = hyprpaper
#exec-once = swww-daemon
#exec-once = glava #GLava
#exec-once = alacritty --option window.opacity=0.0 --class "Background" -e pipes.sh #Pipes
#exec-once = alacritty --option window.opacity=0.0 --class "Background" -e unimatrix -af -c blue -s 96 #Matrix
#exec-once = alacritty --option window.opacity=0.0 --option font.size=14 --class "Background" -e asciiquarium #ASCIIQuarium
exec-once = ~/Data/Projects/Unity/Nisualizer/Builds/Linux/Nisualizer.x86_64

# Workspace 1
exec-once = [workspace 1 silent] $browser

# Social Workspace
$socialWorkspace = 2
exec-once = [workspace $socialWorkspace silent] mumble
exec-once = [workspace $socialWorkspace silent] sleep 1 && element-desktop
exec-once = [workspace $socialWorkspace silent] sleep 3 && Telegram
exec-once = [workspace $socialWorkspace silent] sleep 5 && equibop # Make sure to disable Equibop Settings -> Enable Splash Screen so the main window insta opens

# Special Workspace
$specialWorkspace = special
exec-once = [workspace $specialWorkspace silent] keepassxc
exec-once = [workspace $specialWorkspace silent] xdg-terminal-exec ncmpcpp && sleep 2 && hyprctl dispatch movetoworkspacesilent special:special, title:ncmpcpp
exec-once = [workspace $specialWorkspace silent] sleep 2 && obsidian
exec-once = [workspace $specialWorkspace silent] sleep 3 && obs --startreplaybuffer --disable-shutdown-check

# Change to exec-once if you don't need live reloading
#exec = swww img $background
#exec = export XCURSOR_THEME=$cursor
#exec = export XCURSOR_SIZE=$cursor_size
#exec = hyprctl setcursor $cursor $cursor_size
