# Startup
exec-once = dbus-update-activation-environment --all

# App Tracking
exec-once = fish -c "track_app_usage"

# Settings
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprctl setcursor Nordzy-cursors-white 30

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Daemons
exec-once = pypr
exec-once = dunst
exec-once = hypridle
exec-once = syncthing
exec-once = kdeconnectd
exec-once = kdeconnect-indicator
#exec-once = ollama serve
exec-once = ydotoold # required for Hyprmouse
exec-once = lan-mouse daemon
exec-once = easyeffects --gapplication-service
exec-once = openrgb --startminimized --profile "Night" --server

# Background
#exec-once = swww-daemon
#exec-once = glava #GLava
#exec-once = alacritty --option window.opacity=0.0 --class "Background" -e pipes.sh #Pipes
#exec-once = alacritty --option window.opacity=0.0 --class "Background" -e unimatrix -af -c blue -s 96 #Matrix
#exec-once = alacritty --option window.opacity=0.0 --option font.size=14 --class "Background" -e asciiquarium #ASCIIQuarium
exec-once = ~/Data/Projects/Unity/Nisualizer/Builds/Linux/Nisualizer.x86_64

# Apps
exec-once = ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false
exec-once = ghostty --class=com.ghostty.ncmpcpp -e ncmpcpp

# Workspace 1
exec-once = $browser

# Workspace 2
exec-once = element-desktop
exec-once = sleep 2 && mumble
exec-once = sleep 4 && equibop
exec-once = sleep 10 && flatpak run chat.revolt.RevoltDesktop

# Workspace 9
exec-once = keepassxc
exec-once = sleep 1 && obsidian
exec-once = sleep 2 && obs --startreplaybuffer --disable-shutdown-check

# Change to exec-once if you don't need live reloading
#exec = swww img $background
#exec = export XCURSOR_THEME=$cursor
#exec = export XCURSOR_SIZE=$cursor_size
#exec = hyprctl setcursor $cursor $cursor_size
