schema_version = "1.0.0"
id = "C3DB"
name = "3D Cursors Briefcase"
version = "0.1.8"
tagline = "Store and manage multiple 3D Cursors"
maintainer = "dupoxy"
type = "add-on"
website = "https://projects.blender.org/dupoxy/3d_cursors_briefcase/"
tags = ["3D View"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2024-2026 - dupoxy"]
