# Increase Nvidia's shader cache size to 12GB
__GL_SHADER_DISK_CACHE_SIZE=12000000000

# Increase AMD's shader cache size to 12GB
MESA_SHADER_CACHE_MAX_SIZE=12G

# Enable proton low latency by default
# This should lead to overall better performance, but might cause issues in rare cases
PROTON_DXVK_LOWLATENCY=1

# Disable the DXVK HUD
DXVK_HUD=0
