# Fine-grained zoom controls
Alt+i add video-zoom 0.01
Alt+o add video-zoom -0.01

# Reset zoom and centering
Alt+0 set video-zoom 0; set video-pan-x 0; set video-pan-y 0

# Rotate video
r cycle_values video-rotate 90 180 270 0

# Arrow volume controls
UP add volume 10
DOWN add volume -10
Shift+UP add volume 5
Shift+DOWN add volume -5

# Moving
LEFT seek -5
RIGHT seek 5
Ctrl+LEFT seek -10
Ctrl+RIGHT seek 10
Ctrl+Shift+LEFT seek -60
Ctrl+Shift+RIGHT seek 60
g script-message-to goto toggle-goto 
