schema_version = "1.0.0"

id = "rss_theme_nord"
version = "0.5.2"
name = "RedSavStudios: Nord (Aurora)"
tagline = "Nord Theme With Aurora Accents"
maintainer = "Reddraconi"
type = "theme"
website = "https://gitlab.com/reddraconi/blender-plugins"
tags = ["Dark"]
blender_version_min = "5.0.0"
license = [
  "SPDX:GPL-2.0-or-later"
]
