# Lock KeePassXC
listener {
    timeout = 300
    on-timeout = qdbus6 org.keepassxc.KeePassXC.MainWindow /keepassxc org.keepassxc.KeePassXC.MainWindow.lockAllDatabases && notify-send "KeePassXC locked due to inactivity" && pw-play --media-role=Notification /usr/share/sounds/freedesktop/stereo/message.oga && hyprlock
}
