theme {
    color_scheme = $HOME/.config/qt6ct/colors/Ricer.conf
    icon_theme = Ricer
    style = breeze
    font_fixed = Maple Mono Normal NFP
    font_fixed_size = 13
    font = Maple Mono Normal NFP
    font_size = 13
}

misc {
    single_click_activate = true
    menus_have_icons = true
    shortcuts_for_context_menus = true
}
