background = rgba(ricer.col.background)
base = rgba(ricer.col.button)
text = rgba(ricer.col.foreground)
alternate_base = rgba(ricer.col.button_highlight)
bright_text = rgba(ricer.col.foreground_highlight)
accent = rgba(ricer.col.foreground_highlight_alt)
accent_secondary = rgba(ricer.col.foreground_highlight)
h1_size = ricer.val.max_font_size
h2_size = ricer.val.big_font_size
h3_size = ricer.val.font_size
font_size = ricer.val.small_font_size
small_font_size = ricer.val.min_font_size
icon_theme = "ricer.val.icons"
