# MainMod
$mainMod = SUPER

# Apps
$terminal = ricer.val.terminal
$browser = zen-browser
$textEditor = nvim
$fileManager = yazi

# Window
$activeOpacity = ricer.col.opacity.a01
$inactiveOpacity = ricer.col.opacity_inactive.a01
$rounding = ricer.val.rounding
$roundingPower = ricer.val.roundingPower
$borderSize = ricer.val.outline_size
$borderRotation = ricer.val.outline_rotation\deg
$borderFadeAnimation = ricer.val.outline_fade_animation
$borderFadeDuration = ricer.val.outline_fade_duration
$borderFadeBezier = ricer.val.outline_fade_bezier
$borderRotationAnimation = ricer.val.outline_rotation_animation
$borderRotationDuration = ricer.val.outline_rotation_duration
$borderRotationBezier = ricer.val.outline_rotation_bezier
$borderRotationType = ricer.val.outline_rotation_type
$borderActiveCol = rgba(ricer.col.outline.hexa) rgba(ricer.col.outline_alt.hexa) $borderRotation
$borderInactiveCol = rgba(ricer.col.outline_disabled.hexa) rgba(ricer.col.outline_disabled_alt.hexa) $borderRotation
$gapsIn = ricer.val.gapsIn
$gapsOut = ricer.val.gapsOut
$blur = ricer.val.blur
$blurSize = ricer.val.blurSize
$blurPasses = ricer.val.blurPasses
$shadowCol = rgba(ricer.col.shadow.hexa)
$shadowInactiveCol = rgba(ricer.col.shadow_inactive.hexa)

# Font
$font = ricer.val.font
$fontSize = ricer.val.font_size

# Theme
$theme = ricer.val.gtk_theme
$background = ricer.val.bg
$bgCol = ricer.col.background
$fgCol = ricer.col.foreground
$bgColA = ricer.col.background.hexa
$termColors = LS_COLORS,di=#ricer.col.foreground_alt:fi=#ricer.col.foreground:ln=#ricer.col.link:pi=#ricer.col.link:so=#ricer.col.br_blue:bd=#ricer.col.br_blue:cd=#ricer.col.br_blue:or=#ricer.col.br_red:mi=#ricer.col.br_red:ex=#ricer.col.br_green

# Cursor
$cursor = ricer.val.cursor
$cursorSize = ricer.val.cursor_size
$cursorRot = ricer.val.cursor_rot

# Animation
$animationDuration = ricer.val.animationDuration
$animationCurve = ricer.val.animationEasing
bezier = myBezier, 0.05, 0.9, 0.1, 1.05
bezier = linear, 0.0, 0.0, 1.0, 1.0
bezier = quad, 0.45, 0, 0.55, 1
bezier = quadOut, 0.5, 1, 0.89, 1
bezier = expo, 0.87, 0, 0.13, 1
bezier = expoIn, 0.7, 0, 0.84, 0
bezier = expoOut, 0.16, 1, 0.3, 1
bezier = overshoot, 0.25, 1.75, 0, 0.9

# Group
$groupBorder = rgba(ricer.col.outline.hexa) rgba(ricer.col.outline_alt.hexa) 90deg
$groupBorderInactive = rgba(ricer.col.outline_inactive.hexa) rgba(ricer.col.outline_inactive_alt.hexa) 270deg
$groupBorderLocked = rgba(ricer.col.yellow.hexa)
$groupBorderLockedInactive = rgba(ricer.col.outline_inactive.hexa)


# Source Configs
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/render.conf
source = ~/.config/hypr/cursor.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/HyprlandUnityFix/UnityFix.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/dwindle.conf
source = ~/.config/hypr/master.conf
source = ~/.config/hypr/scrolling.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/ecosystem.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/group.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/plugins.conf
exec-once = sleep 5

# This is needed for shaders using time, delete this line to potentially improve performance
#debug:damage_tracking = off
