[flavor]
dark = "everforest-medium"

[filetype]
rules = [
    { url = "*/", fg = "brightblue" },
    { url = "*",  fg = "brightcyan" },
]

[icon]
globs = [
    { url = "*/", text = "◈" },
    { url = "*",  text = "🞋" },
]
