schema_version = "1.0.0"

id = "Black"
version = "5.0.4"
name = "Black"
tagline = "A black theme, probably the blackest one"
maintainer = "Gurra"
type = "theme"


tags = ["Dark"]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-2.0-or-later",
]
