db_file "~/Data/Music/Database"
log_file "syslog"
auto_update "yes"
music_directory "~/Data/Music/"
playlist_directory "~/Data/Music/Playlists"
pid_file "~/.config/mpd/pid"
state_file "~/.config/mpd/state"
sticker_file "~/Data/Music/Sticker.sql"
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
#restore_paused "yes" # This somehow fucking makes it so that volume resets to 100%

# Replay Gain
replaygain        "track"
replaygain_preamp "0"
replaygain_limit  "yes"

# Global format
audio_output_format    "96000:24:2"

# Main audio output
audio_output {
    type            "pipewire"
    name            "MPD PipeWire Output"
}

# Keep your FIFO for visualizers (this is fine as-is)
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "96000:24:2"
}
