[general]
live_config_reload = true

[window]
padding = {x = 10, y = 10}
opacity = 1

[font]
normal = { family = "Maple Mono NF CN", style = "Regular" }
bold = { family = "Maple Mono NF CN", style = "Bold" }
italic = { family = "Maple Mono NF CN", style = "Italic" }
bold_italic = { family = "Maple Mono NF CN", style = "Bold Italic" }
size = 16

[colors]
footer_bar = { foreground = "#A3C5CC", background = "#081D26" }
transparent_background_colors = true

[colors.primary]
foreground = "#A3C5CC"
background = "#081D26"
dim_foreground = "#849FA5"
bright_foreground = "#B7DCE5"

[colors.search]
matches = { foreground = "#A3C5CC", background = "#081D26" }
focused_match = { foreground = "#B7DCE5", background = "#081D26" }

[colors.hints]
start = { foreground = "#A3C5CC", background = "#081D26" }
end = { foreground = "#849FA5", background = "#081D26" }

[colors.normal]
black = "#081D26"
red = "#661F1F"
green = "#1F6628"
yellow = "#66661F"
blue = "#1F5A66"
magenta = "#4D1F66"
cyan = "#1F665A"
white = "#A3C5CC"

[colors.bright]
black = "#0C2E3F"
red = "#7F2626"
green = "#267F32"
yellow = "#7F7F26"
blue = "#266F7F"
magenta = "#5F267F"
cyan = "#267F6F"
white = "#B7DCE5"

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }

#alacritty-smooth-cursor settings
#smooth_motion = true
#smooth_motion_factor = 0.2
#smooth_motion_spring = 0.5
