set -g history-limit 50000
set -s escape-time 0
set -g base-index 1
set -g pane-base-index 1

set -g mouse on

set -g mode-keys vi
set -g status-keys vi

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Don't copy nor clear selection when m1 is released
unbind -Tcopy-mode MouseDragEnd1Pane

bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

set -g status-style bg=default
set -g status-justify centre
set -g status-right-length 40
set -g status-right-length 60
set -g status-left "#[fg=default]#{user}☦#h | "
set -g status-right "#[fg=default]%Y-%m-%d %H:%M "
