monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-Audeze_LLC.*"
      }
    ]
    actions = {
      update-props = {
        audio.format    = "S24LE"
        audio.rate      = 96000
        audio.channels  = 2
        api.alsa.period-size = 256
        api.alsa.headroom = 256
      }
    }
  }
]
