monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_input.usb-Kingston_HyperX.*"
      }
    ]
    actions = {
      update-props = {
        audio.rate = 48000
      }
    }
  }
]
